# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1234123412341234d3db5b0977be45b11691f460aa80c6030f6b6ed812f5a18d8450fc63244747ea0657a95fa300412c64810644c3d22ae382f7050d549dd26c
  mailer_domain: "lvh.me:3000"
  sentry_dsn_private: ""
  sentry_dsn_public: ""

  doc_name: <%= ENV.fetch("DOC_NAME", "App Name") %>
  doc_source: <%= ENV.fetch("DOC_SOURCE", "Based On") %>

test:
  secret_key_base: 241243123412341234e78f9f6033e4a41fda4f2f78a1ae671a387d63de42f8bec84fd6dfeb1a72ac1056e427b04ec986bdc82743b7990d7d484beb1b0b0edf92
  mailer_domain: "lvh.me:3000"
  sentry_dsn_private: ""
  sentry_dsn_public: ""

  doc_name: <%= ENV.fetch("DOC_NAME", "App Name") %>
  doc_source: <%= ENV.fetch("DOC_SOURCE", "Based On") %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", "241243123412341234e78f9f6033e4a41fda4f2f78a1ae671a387d63de42f8bec84fd6dfeb1a72ac1056e427b04ec986bdc82743b7990d7d484beb1b0b0edf92") %>
  mailer_domain: <%= ENV["DOMAIN_NAME"] %>
  sentry_dsn_private: <%= ENV["SENTRY_DSN_PRIVATE"] %>
  sentry_dsn_public: <%= ENV["SENTRY_DSN_PUBLIC"] %>

  doc_name: <%= ENV.fetch("DOC_NAME", "App Name") %>
  doc_source: <%= ENV.fetch("DOC_SOURCE", "Based On") %>
